# Print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[username]
style_user = "green bold"
format = "[$user]($style) "
show_always = true

[hostname]
ssh_only = false
format =  "@ [$hostname](bold red) "

[conda]
format = "[$symbol$environment](dimmed green) "

[julia]
symbol = "∴ "
style = "bold red"
